### ISSUE TITLE
Clarification on "not ready to use" in README

### ISSUE THREAD

**Issue by jung-kim** [kostya-sh/parquet-go#4]
> WARNING: totally not ready to use

Could you be more specific on what is not ready?

**Comment by kostya-sh** [comment]
It would be much easier to describe what is ready ;) The only thing that is completely implemented is reading parquet file metadata. Reading boolean and string fields are somewhat supported.

On a serious note this package in its current state is completely unusable (hence the WARNING in the README). I am not actively working on this package as I have no use for it currently.

If you are planning to work on a Go package for reading/writing parquet format I will be happy to answer any questions.

**Comment by jung-kim** [comment]
Our lives could been so much easier if I wouldn't have to convert these parquet files...
