### ISSUE TITLE
Just check progress

### ISSUE THREAD

**Issue by chrislusf** [kostya-sh/parquet-go#5]
I am working on a go based map reduce system.

https://github.com/chrislusf/gleam

It'll be really nice if this go parquet library can work.

**Comment by chrislusf** [comment]
getting this error:

unsupported compression codec: GZIP

This is a parquet file generated by Spark by default.

**Comment by kostya-sh** [comment]
@chrislusf, as REAME says this library is completely unusable at the moment. Besides currently I do not have time and interest to work on it. Feel free to fork it and pick it up from where I left. I will be happy to offer any advice if necessary.
